### PR TITLE
NXP-25202: style unresolved nuxeo-app

### PR DESCRIPTION
**Pull request by Gabez0r**
Note that the `[unresolved]` selector precedes all css rules to prevent bleed on shady css.

### CODE REVIEW

**Comment by guirenard** [comment]
:+1:

**Comment by Gabez0r** [comment]
I agree that the css file would be more elegant and maintainable, but it's an additional request that can take a little bit on slower networks. So I believe it would be a fair tradeoff, since we shouldn't be changing this css too often...

**Comment by Gabez0r** [comment]
Ended up moving the styles to a separate `css` file because we can inline the file directly on `index.jsp` as a static include, thus saving that additional request. :)

**Comment by guirenard** [comment]
:+1:

**Comment by nmpcunha** [comment]
👍

**Pull request merged**
