### PR TITLE
WEBUI-1355: disable unit tests using for firefox

### PR DESCRIPTION
**Pull request by rakeshkumar1019**
https://jira.nuxeo.com/browse/WEBUI-1355
Older ticket : https://jira.nuxeo.com/browse/WEBUI-1314

### CODE REVIEW

**Review by swarnadipa-dev — DISMISSED** [review]

**Review by rahuljain-dev — DISMISSED** [review]

**Comment by rahuljain-dev** [comment]
@rakeshkumar1019 please add ticket reference/comment when we will revert this action

**Comment by rakeshkumar1019** [comment]
> @rakeshkumar1019 please add ticket reference/comment when we will revert this action

added

**Review by poonamyadav252 — DISMISSED** [review]
Kindly add a comment on top of the commented code (e.g. why we commented on the code and when we will fix it)and wrap it under a single-line comment.

**Comment by rakeshkumar1019** [comment]
> Kindly add a comment on top of the commented code (e.g. why we commented on the code and when we will fix it)and wrap it under a single-line comment.

added

**Review by rahuljain-dev — DISMISSED** [review]

**Review by swarnadipa-dev — DISMISSED** [review]

**Review by rahuljain-dev — APPROVED** [review]

**Review by Nishant0928 — APPROVED** [review]

**Review by arupmmi07 — APPROVED** [review]

**Review by poonamyadav252 — APPROVED** [review]

**Pull request merged**
