### PR TITLE
NXP-24917: bind node_modules and bower_components deletion on clean p…

### PR DESCRIPTION
**Pull request by guirenard**
…hase + introduce pipeline profile

### CODE REVIEW

**Comment by afjusto** [comment]
👍

**Comment by Gabez0r** [comment]
👍

**Comment by jcarsique** [comment]
:-1:

**Comment by guirenard** [comment]
`<target unless="${skipNpmInstall}">` does work ... Please explain why it won't work (since it is working)

The purpose of this profile is to let the pipeline prepare the bower dependencies since we want to use `nuxeo-ui-elements` or `nuxeo-elements` fetched from a branch other than master which has related changes to be validated by functional tests run in the mp.

**Pull request merged**
