### PR TITLE
NXP-26580: fix EN label

### PR DESCRIPTION
**Pull request by manonlumeau**

### CODE REVIEW

**Comment by nmpcunha** [comment]
Thanks for your contribution @manonlumeau!
We'll ask you to have a more precise message. Instead of `fix EN label` we would suggest something like 'fix EN graph error label'.

**Comment by nmpcunha** [comment]
👍

**Comment by Gabez0r** [comment]
Missing ticket id on commit message.

**Comment by nmpcunha** [comment]
👍

**Pull request merged**
