### PR TITLE
WEBUI-805: Add file to schemas for collection content

### PR DESCRIPTION
**Pull request by utsavsahaa**

### CODE REVIEW

**Review by Gabez0r — COMMENTED** [review]
Looks good to me, great job! But please, create a matching WEBUI ticket and ament the commit. Thank you.

**Review by richardsd — COMMENTED** [review]
Looks good to me too. Just follow Gabriel recommendations first 👍

**Review by richardsd — CHANGES_REQUESTED** [review]
Everything looks great 👍 , but can you just remove the extra `"` from the commit message 😬

**Comment by utsavsahaa** [comment]
> Everything looks great 👍 , but can you just remove the extra `"` from the commit message 😬

Oh Boy , i made a mess.
Updated now.

**Review by richardsd — APPROVED** [review]

**Comment by richardsd** [comment]
> > Everything looks great 👍 , but can you just remove the extra `"` from the commit message 😬
> 
> Oh Boy , i made a mess. Updated now.

😂 No problem, issue fixed 👍 Thanks @utsavsahaa

**Review by Gabez0r — APPROVED** [review]

**Pull request merged**
