### PR TITLE
NXP-26938: expose variables to configure the create and edit dialog sizes (Backport 10.10)

### PR DESCRIPTION
**Pull request by semisse**

### CODE REVIEW

**Comment by semisse** [comment]
Pipeline ok: https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-sfialho-10.10/2/

**Comment by guirenard** [comment]
:+1:

**Comment by Gabez0r** [comment]
👍

**Comment by guirenard** [comment]
:+1:

**Comment by semisse** [comment]
Since we've changed the approach to this problem, I'm closing this PR.
https://github.com/nuxeo/nuxeo-web-ui/pull/610

**Pull request closed without merging**
