### PR TITLE
ELEMENTS-902: add defaultTime attribute to nuxeo-date-picker endDate (Backport 9.10)

### PR DESCRIPTION
**Pull request by semisse**

### CODE REVIEW

**Comment by guirenard** [comment]
Please use NXP-27025 in the commit message instead.

**Comment by Gabez0r** [comment]
👍

**Comment by guirenard** [comment]
Let's wait for a PR for https://jira.nuxeo.com/browse/ELEMENTS-902

**Comment by guirenard** [comment]
:+1:

**Comment by Gabez0r** [comment]
👍

**Pull request merged**
