### PR TITLE
NXP-25786: add target document and observer for recent documents

### PR DESCRIPTION
**Pull request by nmpcunha**

### CODE REVIEW

**Comment by nmpcunha** [comment]
Functional Tests: https://github.com/nuxeo/plugin-nuxeo-web-ui/pull/91

**Comment by guirenard** [comment]
Unless I missed something, the following should simply fix the issue:

```
m3 fox@fox-laptop:~/workspace/nuxeo/addons/nuxeo-web-ui$ git diff
diff --git i/elements/nuxeo-recent-documents/nuxeo-recent-documents.html w/elements/nuxeo-recent-documents/nuxeo-recent-documents.html
index 787d8c89..80caad47 100644
--- i/elements/nuxeo-recent-documents/nuxeo-recent-documents.html
+++ w/elements/nuxeo-recent-documents/nuxeo-recent-documents.html
@@ -112,6 +112,7 @@ limitations under the License.
       },
 
       add: function(doc) {
+        this.remove(doc);
         this.$.storage.add(doc);
         if (this.documents.length > this.maxSize) {
           this.splice('documents', -1, 1);
```
since this method is called whenever we navigate to a document (including right after editing one)

**Comment by nmpcunha** [comment]
Thanks! It is true that it simplifies the solution.
I didn't apply the diff directly in order to improve the semantics and readability.

**Comment by guirenard** [comment]
:+1:

**Comment by Gabez0r** [comment]
👍

**Pull request merged**
