### PR TITLE
WEBUI-904: added aria-expanded to quick search button to enable expan…

### PR DESCRIPTION
**Pull request by swarnadipa-dev**
…d/collapse state announced by screen reader

### CODE REVIEW

**Review by rakeshkumar1019 — COMMENTED** [review]
Please see this comment if these changes also apply here.https://github.com/nuxeo/nuxeo-web-ui/pull/1630#discussion_r1007837156

**Review by rakeshkumar1019 — DISMISSED** [review]

**Review by Nisha-QA — DISMISSED** [review]
Looks good

**Review by SnehalNaik-DEV — DISMISSED** [review]
Looks good

**Review by GuruprasadAnk1996 — DISMISSED** [review]

**Review by rakeshkumar1019 — DISMISSED** [review]

**Review by rajatgoel-gl — COMMENTED** [review]
Going forward kindly do not touch the tag if we are not changing them. Approved for now.
image

**Review by semisse — CHANGES_REQUESTED** [review]
Since `aria-expanded` is an attribute, we should be binding the attribute itself and not the property:
https://polymer-library.polymer-project.org/3.0/docs/devguide/data-binding#attribute-binding

```suggestion
      aria-expanded$="[[toggled]]"
```

Please, also keep in mind what @rajatgoel-gl mentioned. Only introduce the changes that you need (in this case, please leave the `on-tap="toggle"` on line 302).

**Comment by swarnadipa-dev** [comment]
> Since `aria-expanded` is an attribute, we should be binding the attribute itself and not the property: https://polymer-library.polymer-project.org/3.0/docs/devguide/data-binding#attribute-binding
> 
> ```
>       aria-expanded$="[[toggled]]"
> ```
> 
> Please, also keep in mind what @rajatgoel-gl mentioned. Only introduce the changes that you need (in this case, please leave the `on-tap="toggle"` on line 302).

@semisse using aria-expanded$ instead of aria-expanded is not working correctly, as in Chrome screen reader is not announcing the expanded/collapsed state. I have taken reference from 2 other files (the only examples in the codebase) , nuxeo-document-tree.js and nuxeo-checkbox-aggregator.js, where aria-expanded has been used and not aria-expanded$. 

@rajatgoel-gl  Have implemented the change as requested

**Review by semisse — APPROVED** [review]

**Review by GuruprasadAnk1996 — APPROVED** [review]

**Review by rakeshkumar1019 — APPROVED** [review]

**Review by SnehalNaik-DEV — APPROVED** [review]
Looks good

**Review by rajatgoel-gl — APPROVED** [review]

**Pull request merged**
