### PR TITLE
WEBUI-873: make nuxeo-user-tag accessible

### PR DESCRIPTION
**Pull request by GuruprasadAnk1996**
https://jira.nuxeo.com/browse/WEBUI-873

Accessibility test will pass here  once the merge of https://github.com/nuxeo/nuxeo-elements/pull/601

### CODE REVIEW

**Review by poonamyadav252 — CHANGES_REQUESTED** [review]
Accessibility check is failed, kindly take an action on it.

**Review by swarnadipa-dev — APPROVED** [review]
Looks good

**Comment by GuruprasadAnk1996** [comment]
> Accessibility check is failed, kindly take an action on it.

Once the merge in https://github.com/nuxeo/nuxeo-elements/pull/601, this Accessibility will pass

**Review by poonamyadav252 — APPROVED** [review]
As @GuruprasadAnk1996 mentioned, Accessibility checks will be passed after merging `Element` https://github.com/nuxeo/nuxeo-elements/pull/601 PR, So I mark as approved it.

**Review by richardsd — APPROVED** [review]

**Review by rajatgoel-gl — CHANGES_REQUESTED** [review]
Let me know when all checks are passed. I will re-review.

**Review by rajatgoel-gl — APPROVED** [review]

**Pull request merged**
