### PR TITLE
WEBUI-892: announce as loading, while tree is selected

### PR DESCRIPTION
**Pull request by poonamyadav252**

### CODE REVIEW

**Review by swarnadipa-dev — DISMISSED** [review]
Looks good

**Review by rakeshkumar1019 — DISMISSED** [review]

**Comment by GuruprasadAnk1996** [comment]
Is there any necessity of changing aria-hidden to false in paper-spinner? I guess this will not make any change in screen-reader

**Review by GuruprasadAnk1996 — COMMENTED** [review]
Is there any necessity of changing aria-hidden to false in paper-spinner?

**Review by GuruprasadAnk1996 — APPROVED** [review]

**Review by swarnadipa-dev — APPROVED** [review]
Looks good

**Review by rakeshkumar1019 — APPROVED** [review]

**Review by rajatgoel-gl — APPROVED** [review]

**Pull request merged**
