### PR TITLE
WEBUI-794: display a label instead of doc id for the root document(BackPort 10.10)

### PR DESCRIPTION
**Pull request by GuruprasadAnk1996**
https://jira.nuxeo.com/browse/WEBUI-794

### CODE REVIEW

**Review by rakeshkumar1019 — DISMISSED** [review]
looks good

**Review by SnehalNaik-DEV — DISMISSED** [review]
Looks good!

**Comment by semisse** [comment]
The commit should not reference the backport information, and should be exactly the same message of the original PR.
We only use the `(Backport 10.10)` information as the PR title, in Github, to give a heads-up for the reviewer. Please amend the commit message and remove the backport reference.

**Review by semisse — CHANGES_REQUESTED** [review]
Please amend the commit message (see my previous comment)

**Review by richardsd — COMMENTED** [review]
Please review Sam's comments about the commit message and backport 🙂

**Review by rakeshkumar1019 — APPROVED** [review]
looks good

**Review by semisse — APPROVED** [review]

**Pull request merged**
