### PR TITLE
WEBUI-226: remove ai addon

### PR DESCRIPTION
**Pull request by andreinechaev**

### CODE REVIEW

**Review by andreacornaglia — APPROVED** [review]

**Review by Gabez0r — COMMENTED** [review]
Missing [./images/ai](images/ai).

Also, what is the target version for this change? The ticket's fix version is marked for 2.4.39, which is HF39 for 10.10, which I assume is a mistake?

**Comment by andreinechaev** [comment]
> Missing [./images/ai](images/ai).
> 
> Also, what is the target version for this change? The ticket's fix version is marked for 2.4.39, which is HF39 for 10.10, which I assume is a mistake?

Yes, thank you. Assuming this will be available in the next master release

**Comment by andreinechaev** [comment]
@Gabez0r changed the target and fix version to 3.x

**Comment by Gabez0r** [comment]
@andreinechaev Thank you. If this is also for LTS 2021, please open the PR on the maintenance-3.0.x branch as well.

**Review by Gabez0r — APPROVED** [review]

**Review by semisse — APPROVED** [review]

**Pull request merged**
