### PR TITLE
WEBUI-1169: Fix save as button after refresh when drawer is closed

### PR DESCRIPTION
**Pull request by rahuljain-dev**
https://jira.nuxeo.com/browse/WEBUI-1169

### CODE REVIEW

**Review by swarnadipa-dev — COMMENTED** [review]
Please check whether removing this line has an impact on the bug/ticket for which this was written originally.

**Comment by rahuljain-dev** [comment]
> Please check whether removing this line has an impact on the bug/ticket for which this was written originally.

Checking

**Review by swarnadipa-dev — COMMENTED** [review]
Please check this PR
This line was added as part of the fix.
https://github.com/nuxeo/nuxeo-web-ui/pull/1757

**Comment by rahuljain-dev** [comment]
> Please check this PR This line was added as part of the fix. #1757

As per the discussion, it is fixed and doesn't impact existing changes with new commit

**Review by rakeshkumar1019 — APPROVED** [review]

**Review by swarnadipa-dev — APPROVED** [review]

**Review by rajatgoel-gl — APPROVED** [review]

**Pull request merged**
